apiVersion: v1
kind: Service
metadata:
  name: wayapos-agency-service
  labels:
    app: wayapos-agency-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: wayapos-agency-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wayapos-agency-service
  labels:
    app: wayapos-agency-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wayapos-agency-service
  template:
    metadata:
      labels:
        app: wayapos-agency-service
    spec:
      containers:
      - name: wayapos-agency-service
        image: 863852973330.dkr.ecr.eu-west-2.amazonaws.com/wayapos-agency-service:imgtag
        resources:
          requests:
            memory: "200Mi"
        envFrom:
        - configMapRef:
            name: common-services-config
        ports: 
        - name: http
          containerPort: 80 
        volumeMounts:
        - name: config-file
          mountPath: "/app/application-cfgprofile.yml"  # "secret-file" file will be created in "/app" directory
          subPath: application.yml
      nodeSelector:
        node.kubernetes.io/description: cfgprofile    
      volumes:
        - name: config-file
          secret:
            secretName: wayapos-agency-service-config-file # name of the Secret
