apiVersion: v1
kind: Service
metadata:
  name: external-service
  labels:
    app: external-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: external-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-service
  labels:
    app: external-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-service
  template:
    metadata:
      labels:
        app: external-service
    spec:
      containers:
      - name: external-service
        image: 863852973330.dkr.ecr.eu-west-2.amazonaws.com/external-service:imgtag
        envFrom:
        - configMapRef:
            name: common-services-config
        ports: 
        - name: http
          containerPort: 80 
        volumeMounts:
        - name: config-file
          mountPath: "/app/application-cfgprofile.yml"  # "secret-file" file will be created in "/app" directory
          subPath: application.yml
      volumes:
        - name: config-file
          secret:
            secretName: external-service-config-file # name of the Secret
